steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--build-arg=AUTH_SECRET=$_AUTH_SECRET'
      - '--build-arg=AUTH_GOOGLE_ID=$_AUTH_GOOGLE_ID'
      - '--build-arg=AUTH_GOOGLE_SECRET=$_AUTH_GOOGLE_SECRET'
      - '--build-arg=DATABASE_URL=$_DATABASE_URL'
      - '--build-arg=RAZORPAY_KEY=$_RAZORPAY_KEY'
      - '--build-arg=RAZORPAY_SECRET=$_RAZORPAY_SECRET'
      - '--build-arg=AUTH_TRUST_HOST=$_AUTH_TRUST_HOST'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: asia-south1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 6f098bc3-ca01-452c-99b1-29b3f2519243
  _SERVICE_NAME: tiara-test-web
  _DEPLOY_REGION: asia-south1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - tiara-test-web
